'use strict';

const { test, expect } = require('@playwright/test');

// Slug generated by SlugHelper.Slugify("How do I defend stale laboratory activities?")
// Rules: toLower, strip non [a-z0-9 -], spaces -> dashes, trim dashes.
const KNOWN_SLUG = 'how-do-i-defend-stale-laboratory-activities';

test.describe('FAQs Page (/faqs)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/faqs');
    await page.waitForLoadState('load');
    // faq.js attaches listeners on DOMContentLoaded via site.js.
    await page.waitForFunction(() => typeof window.initFaqToc === 'function');
  });

  // ── Static structure ────────────────────────────────────────────────────────

  test('page loads and shows at least one FAQ section', async ({ page }) => {
    // Each course group is wrapped in <section data-course-tags="…">.
    const sections = page.locator('section[data-course-tags]');
    await expect(sections.first()).toBeVisible({ timeout: 5000 });
    expect(await sections.count()).toBeGreaterThan(0);
  });

  test('course filter chips are rendered', async ({ page }) => {
    const chips = page.locator('.course-filter-chip');
    await expect(chips.first()).toBeVisible();
    expect(await chips.count()).toBeGreaterThan(0);
  });

  test('FAQ accordion items (<details>) are collapsed by default', async ({ page }) => {
    const firstDetails = page.locator('details').first();
    await expect(firstDetails).toBeAttached();
    const isOpen = await firstDetails.evaluate((el) => el.open);
    expect(isOpen).toBe(false);
  });

  test('TOC links (data-faq-target) are rendered', async ({ page }) => {
    const tocLinks = page.locator('[data-faq-target]');
    expect(await tocLinks.count()).toBeGreaterThan(0);
    await expect(tocLinks.first()).toBeVisible();
  });

  // ── Filter interaction ──────────────────────────────────────────────────────

  test('clicking a filter chip activates it and hides non-matching sections', async ({ page }) => {
    const chips = page.locator('.course-filter-chip');
    if (await chips.count() === 0) test.skip();

    await chips.first().click();

    // At least one section with a matching tag remains visible.
    await page.waitForFunction(
      () => {
        const sections = document.querySelectorAll('section[data-course-tags]');
        return Array.from(sections).some((s) => s.style.display !== 'none');
      }
    );

    await expect(page.locator('#course-filter-clear')).toBeVisible();
  });

  // ── Accordion interaction via TOC ───────────────────────────────────────────

  test('clicking a TOC link opens the corresponding accordion', async ({ page }) => {
    const tocLink = page.locator('[data-faq-target]').first();
    if (await tocLink.count() === 0) test.skip();

    const targetId = await tocLink.getAttribute('data-faq-target');
    await tocLink.click();

    // faq.js sets details.open = true and scrolls to it.
    await page.waitForFunction(
      (id) => {
        const el = document.getElementById(id);
        return el && el.tagName === 'DETAILS' && el.open === true;
      },
      targetId
    );
  });

  test('clicking a TOC link updates the URL hash via replaceState', async ({ page }) => {
    const tocLink = page.locator('[data-faq-target]').first();
    if (await tocLink.count() === 0) test.skip();

    const targetId = await tocLink.getAttribute('data-faq-target');
    await tocLink.click();

    // faq.js uses history.replaceState, not pushState, so waitForURL sees the
    // hash update but does not create a new history entry.
    await page.waitForFunction(
      (id) => window.location.hash === '#' + id,
      targetId
    );
    expect(page.url()).toContain('#' + targetId);
  });

  // ── Deep-link / hash navigation ─────────────────────────────────────────────

  test('loading /faqs with a hash opens the matching accordion', async ({ page }) => {
    // Navigate fresh with hash so _openDetailsForHash runs on load.
    await page.goto(`/faqs#${KNOWN_SLUG}`);
    await page.waitForLoadState('load');
    await page.waitForFunction(() => typeof window.initFaqToc === 'function');

    await page.waitForFunction(
      (id) => {
        const el = document.getElementById(id);
        return el && el.open === true;
      },
      KNOWN_SLUG
    );
  });

  test('a hashchange event opens the matching accordion', async ({ page }) => {
    // Page is already at /faqs (from beforeEach without hash).
    // Programmatically update the hash to simulate browser back/forward.
    await page.evaluate((id) => {
      window.location.hash = id;
    }, KNOWN_SLUG);

    // The hashchange listener in faq.js should open the accordion.
    await page.waitForFunction(
      (id) => {
        const el = document.getElementById(id);
        return el && el.open === true;
      },
      KNOWN_SLUG
    );
  });
});
